import './globals.css'
import { Roboto } from 'next/font/google'
import Navbar from '@/components/navbar/navbar'
import { myUser } from './actions/getUser'

const roboto = Roboto({
  weight: '500',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Trustmark Student Project',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const myCurrentUser = await myUser();

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar
        myUser={myCurrentUser}
         />
        {children}
      </body>
    </html>
  )
}
