import './globals.css'
import { Roboto } from 'next/font/google'
import Navbar from '@/components/navbar/navbar'

const roboto = Roboto({
  weight: '500',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Trustmark Student Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
